name: Connect 4

on:
  issues:
    types: [opened]

jobs:
  move:
    permissions:
      issues: write
      contents: write
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'Connect4:')

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Play Connect 4
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY_OWNER: ${{ github.repository_owner }}
        run: |
          pip install -r .github/scripts/connect4/requirements.txt
          python .github/scripts/connect4/main.py

      - name: Commit and push changes
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_AUTHOR: ${{ github.event.issue.user.login }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --staged --quiet || git commit -m "${ISSUE_TITLE} by ${ISSUE_AUTHOR}"
          git push
